name: Deploy iOS

on: [push, workflow_dispatch]

permissions: {}
jobs:
  runPush:
    permissions:
      contents: write # for Update bundles

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Trigger BE build
      if: ${{ github.repository == 'sonphantrung/Mindustry' }}
      run: |
        git clone --depth=1 --branch=main https://github.com/sonphantrung/MindustryiOS-Compiler ../MindustryBuilds
        cd ../MindustryBuilds
        BNUM=$(($GITHUB_RUN_NUMBER + 20000))
        git tag ${BNUM}
        git config --global user.name "Github Actions"
        git push https://sonphantrung:${{ secrets.API_TOKEN_GITHUB }}@github.com/sonphantrung/MindustryiOS-Compiler ${BNUM}
